### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MikhailDemchenko** [MikhailDemchenko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Miklouho-Maclayenko** [comment]
Голливудская звезда первой величины, актёр, режиссёр, музыкант, сценарист и продюсер. Обладатель премии «Золотой глобус», трёхкратный номинант на премию «Оскар», девятикратный номинант на премию «Золотой глобус», двукратный номинант на премию BAFTA, номинант на «Золотую пальмовую ветвь» Каннского кинофестиваля, множество других номинаций. Занесен в Книгу рекордов Гиннеса как самый высокооплачиваемый актёр. Фильмы с моим участием собрали более 8 миллиардов долларов в мировом прокате.
Мастерски исполняю роли загадочных эксцентриков, не снимаюсь в шаблонных ролях, каждый мой персонаж - это личность, необычная, яркая, оригинальная.
Наибольшую известность получил за роли в фильмах Тима Бёртона, а также за образ Джека Воробья. Кхм-кхм, _КАПИТАНА_ Джека Воробья!

**Comment by MikhailDemchenko** [comment]
Nice!
